version : 2

sources:
  - name: raw
    schema: gz_raw_data
    description: raw tables
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales informations of greenweenz platform    
      - name: product
        identifier: raw_gz_product
        description: product informations of greenwenz platfom
      - name: ship
        identifier: raw_gz_ship 
        description: shipping information of greenwenz platform